config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :email_preferences, only: [:edit, :update, :index]
  devise_for :salespeople
  devise_for :admins
  devise_for :users

  match "*any" => "application#options", :via => [:options]

  get "/public/redirect/:handle/:variant", to: "public#redirect", as: :cart_redirect, defaults: { format: "html" }
  post "/public/new_request", as: :new_request
  match "/public/get_uid", via: [:get, :post], as: :get_uid, defaults: { format: "json" }
  get "/public/get_links", as: :get_links, defaults: { format: "json" }
  get "/public/set_link", as: :set_link, defaults: { format: "json" }
  get "/public/save_email", as: :save_email, defaults: { format: "json" }
  get "/marketing/opt_out", to: "marketing#opt_out", as: :marketing_opt_out
  get "/marketing/opt_in", to: "marketing#opt_in", as: :marketing_opt_in
  get '/public/unsubscribed', to: 'public#unsubscribed', as: :unsubscribed
  match "public/thanks", via: [:get, :post], to: "public#deposit_redirect", as: :deposit_redirect

  post '/cm/update-subscriptions', to: 'cm#update_subscriptions'

  get "/events/create", to: "events#create"

  resources :events, only: [:show]

  namespace :api do
    resources :requests, only: [:index, :show, :update]
    resources :request_images, only: [:show]
    resources :users, only: [:index, :show]
    patch "/users", to: "users#update"
  end

  namespace :webhooks do
    post "orders_create" => :orders_create
    post "requests_create" => :requests_create
    post "calendly" => :events_create
    post "newsletter" => :newsletter_signup
  end

  match "public/get_ids", via: [:get, :post]

  namespace :admin do
    get 'shopify/add_order' => 'shopify#index'
    post 'shopify/add_order' => 'shopify#add_order'

    resources :users, only: [:index]
    resources :products
    resources :requests do
      member do
        match :opt_out, via: [:all], as: :opt_out
        match :opt_in, via: [:all], as: :opt_in
        match :send_confirmation, via: [:all], as: :send_confirmation
      end
    end

    resources :settings, only: [:update]

    resources :events, only: [:index]

    resources :salespeople do
      collection do
        get :how_to
      end
    end

    resources :marketing_emails, only: [:show, :update, :edit]

    resources :webhooks, only: [:index, :destroy] do
      member do
        get "perform"
      end
    end

    get "/email_statistics" => "email_statistics#index"

    get "shopify/products"
    get "shopify/variants"
    get "shopify/customers"
    get "shopify/customer/:customer_id", to: "shopify#customer", as: "shopify_customer"
    get "shopify/customer", to: "shopify#customer"
    match "shopify/customer/:customer_id/orders", to: "shopify#orders", as: "shopify_customer_orders", via: [:get, :post]
    get "shopify/orders"

    get "test/quote_form" => "test#quote_form", as: "quote_form"
    get "test/post_form" => "test#post_form", as: "post_form"
    get "test/cart" => "test#cart", as: "cart"

    get '/campaign_monitor' => 'campaign_monitor#index'
    put '/campaign_monitor', to: 'campaign_monitor#update'

    get '/shopify_auth' => 'shopify_auth#index'
    get '/shopify_auth/new' => 'shopify_auth#login', as: 'shopify_auth_login'
    get '/shopify_auth/callback' => 'shopify_auth#callback'

    authenticated :salesperson, ->(user) { user&.admin? } do
      mount Sidekiq::Web => "sidekiq"
    end
  end

  get "/admin" => "content#admin", as: "admin_root"

  root to: redirect("/404.html")
end

app/controllers/admin/email_statistics_controller.rb
# frozen_string_literal: true

class Admin::EmailStatisticsController < Admin::BaseController
  def index
    authorize(Admin::EmailStatisticsController)
  end
end

app/helpers/admin/email_statistics_helper.rb
module Admin::EmailStatisticsHelper
  def box_mailer_types_without_marketing_email
    ["confirmation_email", "final_confirmation_email"]
  end

  def all_message_of(mailer_type, template = nil, range = default_range)
    messages = ahoy_messages(range).where(mailer: mailer_type)
    messages = messages.where(utm_campaign: template) if template.present?
    messages
  end

  def opened_messages(mailer_type, template = nil, range = default_range)
    all_message_of(mailer_type, template, range).where.not(opened_at: nil)
  end

  def clicked_messages(mailer_type, template = nil, range = default_range)
    all_message_of(mailer_type, template, range).where.not(clicked_at: nil)
  end

  def open_percentage_of(mailer_type, template = nil, range = default_range)
    percent_of(opened_messages(mailer_type, template, range).count, all_message_of(mailer_type, template, range).count)
  end

  def total_email_open_rate(range = default_range)
    percent_of(ahoy_messages(range).where.not(opened_at: nil).count, ahoy_messages(range).count)
  end

  def total_click_rate(range = default_range)
    percent_of(ahoy_messages(range).where.not(clicked_at: nil).count, ahoy_messages(range).count)
  end

  def click_percentage_of(mailer_type, template = nil, range = default_range)
    percent_of(clicked_messages(mailer_type, template, range).count, all_message_of(mailer_type, template, range).count)
  end

  def ahoy_messages(range = default_range)
    Ahoy::Message.where(sent_at: range)
  end

  def default_range
    [30.days.ago.beginning_of_day..Time.now]
  end

  def percent_of(x, n)
    return "-" unless n.positive?

    number_to_percentage(x / n.to_f * 100, precision: 0)
  end
end

app/views/admin/email_statistics/_header_row.html.erb
<tr>
  <th class=" text-left"><%= title %></th>
  <th class=" text-center"></th>
  <th class=" text-center"></th>
  <th class="text-center bg-gray"><span class="glyphicon glyphicon-envelope"></span></th>
  <th class="text-center bg-gray"><span class="glyphicon glyphicon-eye-open"></span></th>
  <th class="text-center bg-gray"><span class="glyphicon glyphicon-chevron-up"></span></th>
  <th class="text-center"><span class="glyphicon glyphicon-envelope"></span></th>
  <th class="text-center"><span class="glyphicon glyphicon-eye-open"></span></th>
  <th class="text-center"><span class="glyphicon glyphicon-chevron-up"></span></th>
  <th class="text-center bg-gray"><span class="glyphicon glyphicon-envelope"></span></th>
  <th class="text-center bg-gray"><span class="glyphicon glyphicon-eye-open"></span></th>
  <th class="text-center bg-gray"><span class="glyphicon glyphicon-chevron-up"></span></th>
  <th class="text-center"><span class="glyphicon glyphicon-envelope"></span></th>
  <th class="text-center"><span class="glyphicon glyphicon-eye-open"></span></th>
  <th class="text-center"><span class="glyphicon glyphicon-chevron-up"></span></th>
</tr>

app/views/admin/email_statistics/_statistic.html.erb
<%
%>
  <% cache "email-stats/#{email.mailer_method}-#{email.template_name}", expires_in: 15.minutes do %>
    <tr class="text-center">
      <td class="text-primary  text-left">
        <%= link_to label.titleize, email.id ? admin_marketing_email_path(email) : "#" %>
      </td>
      <td class="text-secondary text-center small"><%= email.state %></td>
      <td class="text-secondary text-center small"><%= email.days_after_state_change %> </td>
      <% (0..3).each do |days|
        range = [days.days.ago.beginning_of_day..days.days.ago.end_of_day]
      %>
        <td class="<%= (days % 2 == 0) ? 'bg-gray' : '' %>">
          <%= all_message_of("BoxMailer##{email.mailer_method}", email.template_name, range).count %>
        </td>
        <td class="<%= (days % 2 == 0) ? 'bg-gray' : '' %>">
          <%= open_percentage_of("BoxMailer##{email.mailer_method}", email.template_name, range) %>
        </td>
        <td class="<%= (days % 2 == 0) ? 'bg-gray' : '' %>">
          <%= click_percentage_of("BoxMailer##{email.mailer_method}", email.template_name, range) %>
        </td>
      <% end %>
    </tr>
  <% end %>

app/views/admin/email_statistics/index.html.erb
<div class="row">
  <div class="card">
    <div class="card-header">
      <h2 class="title">Email Statistics</h2>
    </div>
    <div class="card-content table-responsive">
      <table class="table">
        <thead class="text-danger">
        <tr>
          <th></th>
          <th class="text-center">States</th>
          <th class="text-center">Days</th>
          <th colspan="3" class="text-center  bg-gray">Today</th>
          <th colspan="3" class="text-center">Yesterday</th>
          <th colspan="3" class="text-center bg-gray">2 days ago</th>
          <th colspan="3" class="text-center">3 days ago</th>
        </tr>
        </thead>
        <thead class="text-danger">
          <%= render partial: "admin/email_statistics/header_row", locals: { title: "Reminders & Follow-Ups" } %>
        </thead>
        <tbody>
          <% MarketingEmail.not_quotes.order("email_type desc", :state, :days_after_state_change).each do |email| %>
            <%= render partial: "admin/email_statistics/statistic", locals: { email: email, label: email.template_name }%>
          <% end %>
        </tbody>
        <% if current_salesperson.admin? %>
          <thead class="text-danger">
            <%= render partial: "admin/email_statistics/header_row", locals: { title: "Quotes" } %>
          </thead>
          <tbody>
            <% MarketingEmail.quotes.each do |email| %>
              <%= render partial: "admin/email_statistics/statistic", locals: { email: email, label: email.template_name }%>
            <% end %>
          </tbody>
        <% end %>
        <thead class="text-danger">
          <%= render partial: "admin/email_statistics/header_row", locals: { title: "Others" } %>
        </thead>
        <tbody>
          <% box_mailer_types_without_marketing_email.each do |template_name| %>
            <%= render partial: "admin/email_statistics/statistic",
                       locals: { email: MarketingEmail.new(mailer_method: template_name), label: template_name }%>
          <% end %>
        </tbody>
      </table>

    </div>
  </div>
</div>